### ISSUE TITLE
Code lisibility advice

### ISSUE THREAD

**Issue by julon** [MathRobin/sql-update-generator#1]
To correct depending on your own taste :)

- [x] SqlUpdateClass -> SqlUpdate or SqlUpdateString or SqlUpdateStringBuilder
- [ ] Rename addKeyword to setUpperCase(str), addKeyword doesn't describe properly the action
- [x] Remove _ for private properties and functions // it doesn't add value to your code
- [x] Use template strings? Easier to read I believe, less literals and escaping 
- [ ] Inverse ('string' === typeof name) its unnatural to read it
- [x] throw new Error() 
- [ ] Maybe remove _description and _config level to flat things out, replace uppercase by isUpperCase for bool, and maybe replace config by options since I believe you will implement options handling through constructor
- [ ] Refactor type testing with a callback support, less code for managing errors

I think you can extract many small pieces of code to a util class or even rely on external utilities libraries to make your main class smaller and readable. (log.error, strings manipulation, type testing, etc)

👍 :)

**Comment by MathRobin** [comment]
Will not fix the point "Inverse ('string' === typeof name) its unnatural to read it". I believe in the power of yoda style. So I prefer to keep it like this. I agree that it's less natural but even more powerful notation.

**Comment by MathRobin** [comment]
Rest need specific issues.
